# Generated by Django 5.1.1 on 2024-09-23 01:47

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=15, validators=[apps.accounts.models.validate_phone_number]
            ),
        ),
    ]
