# Generated by Django 5.1.1 on 2024-09-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="street_number",
            new_name="home_number",
        ),
    ]
