# Generated by Django 5.1.1 on 2024-09-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_street_number_customuser_home_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="full_name",
            new_name="full_Name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="full_address",
        ),
    ]
