# Generated by Django 5.1.1 on 2024-09-30 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_full_name_customuser_full_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="full_Name",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CPF must be 11 digits", regex="^\\d{11}$"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
