# Generated by Django 5.1.1 on 2024-10-21 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_groups_and_more'),
        ('accounts', '0009_rename_full_name_customuser_full_name_and_more'),
    ]

    operations = [
    ]
