# Generated by Django 5.1.2 on 2024-10-14 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_filial'),
        ('accounts', '0009_rename_full_name_customuser_full_name_and_more'),
    ]

    operations = [
    ]
